plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.groceryapp'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.groceryapp"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    packaging {
        resources.excludes.add("META-INF/LICENSE.md")
        resources.excludes.add("META-INF/NOTICE.md") // Optional, but good to include just in case
    }


    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.18.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'com.google.mlkit:barcode-scanning:17.3.0'
    implementation 'com.google.android.gms:play-services-code-scanner:16.1.0'
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.sun.mail:android-mail:1.6.7'
    implementation 'com.sun.mail:android-activation:1.6.7'
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.cardview
    implementation libs.constraintlayout
    implementation libs.firebase.database
    implementation libs.firebase.firestore
    implementation libs.material
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.recyclerview
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit


}